parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - '@typescript-eslint'

env:
  browser: true
  node: true

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - prettier

overrides:
  - files:
      - src/**/*.{js,ts,tsx}

rules:
  camelcase: error
  padding-line-between-statements:
    - error
    - blankLine: always
      next: '*'
      prev: block-like
    - blankLine: always
      next: block-like
      prev: '*'
    - blankLine: always
      next: return
      prev: '*'
